# -*- coding: utf-8 -*-
"""JP Morgan Chase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySacyLW199P6e_RchSFRdQ0HbCueCg6O

## Load Data & Import Libraries
"""

from google.colab import drive
drive.mount("/content/drive/")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import plotly.express as px
import plotly.graph_objects as go

import json
from datetime import timedelta

from statsmodels.tsa.seasonal import seasonal_decompose

df = pd.read_csv("/content/drive/MyDrive/JP Morgan Chase/Nat_Gas_Data.csv")
df.head()

"""##Exploratory Data Analysis


> EDA & Time-series


"""

# Change Dates col into datetime; sort by date
df['Dates'] = pd.to_datetime(df['Dates'], format="%m/%d/%y")
df = df.sort_values("Dates").reset_index(drop=True)

print(f"Shape: {df.shape}")
print(f"\nDate Range: {df["Dates"].min()} to {df["Dates"].max()}")

# Check gaps between days
diff = df["Dates"].diff().dropna()
print(f"\nDay diff between consecutive rows (describe)\n")
print(diff.dt.days.describe())

# Check for missing months
full_range = pd.date_range(df["Dates"].min(), df["Dates"].max(), freq="ME")
missing = set(full_range) - set(df["Dates"])
print(f"\nMissing Months {sorted(missing)}")

# Summary stats
print(f"\nSummary Stats (Prices):\n{df["Prices"].describe()}\n")

# Plot timeseries
fig = px.line(
    df,
    x="Dates",
    y="Prices",
    title="<b>Natural Gas Prices (Oct '22 to Sep '24)<b>",
    markers=True
)
fig.show()

"""Seasonal Decomposition"""

# Seasonal decomposition
ts = df.set_index('Dates')['Prices']
ts = ts.asfreq('ME')  # ensure monthly freq, will interpolate if needed
if ts.isna().sum() > 0:
    print("\nFilling", ts.isna().sum(), "NaNs via interpolation for decomposition")
    ts = ts.interpolate()

decomposition = seasonal_decompose(ts, model='additive', period=12)

fig = decomposition.plot()
fig.set_size_inches(12, 8)
plt.show()

print("\nSeasonal component (one full year, monthly index 1-12")
seasonal_by_month = decomposition.seasonal.groupby(decomposition.seasonal.index.month).mean()
print(seasonal_by_month.sort_index())

print("\nTrend component (first/last non-nan)")
trend_clean = decomposition.trend.dropna()
print("Trend start:", trend_clean.iloc[0], "on", trend_clean.index[0])
print("Trend end:", trend_clean.iloc[-1], "on", trend_clean.index[-1])
print("Trend change over period:", trend_clean.iloc[-1] - trend_clean.iloc[0])

print("\nResiduals std (noise level)")
print(decomposition.resid.std())

# Year-over-year growth check
yearly_avg = df.groupby(df['Dates'].dt.year)['Prices'].mean()
print("\nYearly average prices:\n", yearly_avg)
print("\nYoY % change:\n", yearly_avg.pct_change() * 100)

"""**Key Findings**: Data is clean with no gaps or missing months; there is a clear upward trend throughout the timeframe, from ~10.4 to ~12.0. However, growth in 2024 slowed to ~2.3% from an average Year over Year change of ~4-5%. **Seasonality**: Dec to Feb winter peaks are highest, +0.55 to +0.69 above the trend line; June is lowest (-0.63), and May to Sep are all below the trend line. **Overall stats**: Prices range from 9.84 to 12.8 with a mean of 11.2.

## Model Fitting

> Model: Linear trend + additive monthly seasonal indices
"""

# Convert date to a continuous numeric "time" variable (fractional years since start)
t0 = df['Dates'].min()

def date_to_t(dates):
    dates = pd.to_datetime(dates)
    delta = dates - t0
    if hasattr(delta, 'dt'):
        return delta.dt.days / 365.25
    return delta.days / 365.25

df['t'] = date_to_t(df['Dates'])
df['month'] = df['Dates'].dt.month

# TRAIN/TEST SPLIT (holdout last 6 months to validate)

HOLDOUT = 6
train = df.iloc[:-HOLDOUT].copy()
test = df.iloc[-HOLDOUT:].copy()

def fit_trend_seasonal(train_df):
    """Fit linear trend on t, then additive monthly seasonal indices on residuals."""
    # Linear trend (Price ~ a*t + b)
    coeffs = np.polyfit(train_df['t'], train_df['Prices'], deg=1)
    slope, intercept = coeffs[0], coeffs[1]

    # Residuals after removing trend
    trend_pred = slope * train_df['t'] + intercept
    resid = train_df['Prices'] - trend_pred

    # Seasonal index per calendar month = mean residual for that month
    seasonal_index = resid.groupby(train_df['month']).mean()
    # Center seasonal indices so they sum to ~0 (keeps trend line as the "mean" line)
    seasonal_index = seasonal_index - seasonal_index.mean()
    # Ensure all 12 months present (fill missing with 0 if a month never appears)
    seasonal_index = seasonal_index.reindex(range(1, 13), fill_value=0)

    return {'slope': slope, 'intercept': intercept, 'seasonal_index': seasonal_index}

model = fit_trend_seasonal(train)
print("Trend: slope =", model['slope'], "per year, intercept =", model['intercept'])
print("\nSeasonal indices (by month):")
print(model['seasonal_index'])

def predict(model, t_values, months):
    trend = model['slope'] * np.asarray(t_values) + model['intercept']
    seasonal = model['seasonal_index'].reindex(months).values
    return trend + seasonal

# Validate on holdout
test_pred = predict(model, test['t'], test['month'])
test_actual = test['Prices'].values

mae = np.mean(np.abs(test_pred - test_actual))
rmse = np.sqrt(np.mean((test_pred - test_actual) ** 2))
mape = np.mean(np.abs((test_pred - test_actual) / test_actual)) * 100

print("\nHoldout validation (last 6 months")
val_df = pd.DataFrame({
    'Date': test['Dates'].values,
    'Actual': test_actual,
    'Predicted': test_pred,
    'Error': test_pred - test_actual
})
print(val_df.to_string(index=False))
print(f"\nMAE:  {mae:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAPE: {mape:.2f}%")

# Compare vs naive baseline (persistence: last known value)
naive_pred = np.full(HOLDOUT, train['Prices'].iloc[-1])
naive_mae = np.mean(np.abs(naive_pred - test_actual))
print(f"\nNaive baseline MAE (last value carried forward): {naive_mae:.4f}")

# REFIT ON FULL DATA
full_model = fit_trend_seasonal(df)
print("\nFull-data model")
print("Trend: slope =", full_model['slope'], "per year, intercept =", full_model['intercept'])
print("Seasonal indices:\n", full_model['seasonal_index'])

fitted = predict(full_model, df['t'], df['month'])
resid_full = df['Prices'] - fitted
print("\nFull-model residual std:", resid_full.std())
print("Full-model R^2:", 1 - np.sum(resid_full**2) / np.sum((df['Prices'] - df['Prices'].mean())**2))

# Save model params for reuse
model_params = {
    't0': t0.strftime('%Y-%m-%d'),
    'slope': full_model['slope'],
    'intercept': full_model['intercept'],
    'seasonal_index': full_model['seasonal_index'].to_dict(),
    'last_known_date': df['Dates'].max().strftime('%Y-%m-%d'),
    'first_known_date': df['Dates'].min().strftime('%Y-%m-%d'),
    'residual_std': float(resid_full.std())
}

# Plot fit vs actual
plt.figure(figsize=(12, 5))
plt.plot(df['Dates'], df['Prices'], 'o-', label='Actual', markersize=4)
plt.plot(df['Dates'], fitted, '--', label='Fitted (trend+seasonal)', linewidth=2)
plt.axvline(test['Dates'].iloc[0], color='gray', linestyle=':', label='Holdout start')
plt.title('Model Fit: Trend + Seasonal vs Actual')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""The model beats the naive baseline by ~45x; trend + seasonality is clearly doing well and not overfitting noise. A **trend slope** of +0.468 per year indicates a ~0.47 USD annual average increase in gas prices. Seasonality pattern indicates increased heating demand during winter (Dec to Feb) and low demand in summer (May, June, August). An **R2** of 0.943 means that the model explains ~94% of variation in the data. A **residual std** of 0.18 means that the remaining noise is small and instructured.

The fitted curve closely tracks the seasonality swings of all 4 years.

## Estimating Prices
"""

# Class that uses historical price data to predict gas prices and extrapolate future prices.

class NatGasPriceModel:
    """
    Estimates natural gas purchase price for any date.

    - For dates within the historical range: linear interpolation between
      known monthly data points (most accurate, grounded in real data).
    - For dates beyond the historical range (future, up to ~1 year out):
      extrapolates using a fitted linear trend + additive monthly seasonal
      index. Returns a point estimate plus a naive confidence interval that
      widens with distance into the future.
    """

    def __init__(self, data, model_params=None):
        self.df = data
        self.first_date = df['Dates'].min()
        self.last_date = df['Dates'].max()

        # Numeric time axis (days since epoch) for interpolation
        self._x_known = df['Dates'].map(pd.Timestamp.toordinal).values
        self._y_known = df['Prices'].values

        if model_params:
            params = model_params
            self.t0 = pd.Timestamp(params['t0'])
            self.slope = params['slope']
            self.intercept = params['intercept']
            self.seasonal_index = {int(k): v for k, v in params['seasonal_index'].items()}
            self.residual_std = params['residual_std']
        else:
            self._fit_trend_seasonal()

    def _fit_trend_seasonal(self):
        """Fallback: fit trend + seasonality directly if no saved params provided."""
        self.t0 = self.first_date
        t = (self.df['Dates'] - self.t0).dt.days / 365.25
        month = self.df['Dates'].dt.month
        slope, intercept = np.polyfit(t, self.df['Prices'], deg=1)
        trend_pred = slope * t + intercept
        resid = self.df['Prices'] - trend_pred
        seasonal_index = resid.groupby(month).mean()
        seasonal_index = seasonal_index - seasonal_index.mean()
        seasonal_index = seasonal_index.reindex(range(1, 13), fill_value=0)
        self.slope = slope
        self.intercept = intercept
        self.seasonal_index = seasonal_index.to_dict()
        self.residual_std = resid.std()

    def _trend_seasonal_estimate(self, date):
        """Model-based estimate: trend + seasonal index for a given date."""
        t = (date - self.t0).days / 365.25
        month = date.month
        return self.slope * t + self.intercept + self.seasonal_index[month]

    def estimate_price(self, date, return_interval=False):
        """
        Estimate gas price on a given date.

        Parameters:

        date : str or datetime-like
            The date to estimate a price for, e.g. '2024-12-15' or '3/15/25'.
        return_interval : bool
            If True, also return a rough +/- confidence range (only meaningful
            for extrapolated/future dates; historical interpolation has no
            interval since it's not a statistical estimate).

        Returns:

        float, or (float, (low, high)) if return_interval=True
        """
        date = pd.Timestamp(date)
        max_future = self.last_date + pd.DateOffset(years=1)

        if date > max_future:
            raise ValueError(
                f"Date {date.date()} is more than 1 year beyond the last known "
                f"data point ({self.last_date.date()}). Extrapolation beyond "
                f"1 year is not supported by this model."
            )

        if self.first_date <= date <= self.last_date:
            # Interpolate between known data points
            price = float(np.interp(date.toordinal(), self._x_known, self._y_known))
            interval = (price, price)  # no uncertainty for grounded interpolation
        elif date < self.first_date:
            # Before data starts: use trend+seasonal model as best-effort backcast
            price = self._trend_seasonal_estimate(date)
            years_out = (self.first_date - date).days / 365.25
            margin = 1.96 * self.residual_std * (1 + years_out)
            interval = (price - margin, price + margin)
        else:
            # Future: extrapolate using trend + seasonal
            price = self._trend_seasonal_estimate(date)
            years_out = (date - self.last_date).days / 365.25
            # Widen interval the further out we extrapolate
            margin = 1.96 * self.residual_std * (1 + years_out)
            interval = (price - margin, price + margin)

        if return_interval:
            return price, interval
        return price


if __name__ == "__main__":
    model = NatGasPriceModel(
        data=df,
        model_params=model_params
    )

    test_dates = [
        '2020-10-31',  # first known date (exact)
        '2022-03-15',  # interior/interpolated
        '2024-09-30',  # last known date (exact)
        '2024-12-15',  # ~2.5 months future
        '2025-06-30',  # ~9 months future
        '2025-09-30',  # exactly 1 year future
        '2020-06-01',  # before data starts (backcast)
    ]

    print(f"{'Date':<12} {'Estimate':>10} {'Low':>8} {'High':>8}")
    for d in test_dates:
        price, (lo, hi) = model.estimate_price(d, return_interval=True)
        print(f"{d:<12} {price:>10.3f} {lo:>8.3f} {hi:>8.3f}")

    # Confirm the >1 year error works
    print("\nTesting the >1 year error ...\n")
    try:
        model.estimate_price('2026-06-01')
    except ValueError as e:
        print(e)

"""## Deliverables: Interactive Chart"""

# Load model
model = NatGasPriceModel(
    data=df,
    model_params=model_params
)

df = model.df

# Build a dense daily timeline: historical (interpolated) + 1 year forward (extrapolated)
hist_dates = pd.date_range(model.first_date, model.last_date, freq='D')
future_dates = pd.date_range(model.last_date + pd.Timedelta(days=1),
                              model.last_date + pd.DateOffset(years=1), freq='D')

hist_prices = [model.estimate_price(d) for d in hist_dates]

future_results = [model.estimate_price(d, return_interval=True) for d in future_dates]
future_prices = [r[0] for r in future_results]
future_lo = [r[1][0] for r in future_results]
future_hi = [r[1][1] for r in future_results]

# Base figure using plotly.express for the historical interpolated line
hist_df = pd.DataFrame({'Date': hist_dates, 'Price': hist_prices, 'Series': 'Historical (interpolated)'})
future_df = pd.DataFrame({'Date': future_dates, 'Price': future_prices, 'Series': 'Forecast (extrapolated)'})
combined = pd.concat([hist_df, future_df], ignore_index=True)

fig = px.line(
    combined, x='Date', y='Price', color='Series',
    title='Natural Gas Price: Historical Interpolation + 1-Year Forecast',
    color_discrete_map={
        'Historical (interpolated)': '#1f77b4',
        'Forecast (extrapolated)': '#ff7f0e'
    }
)
fig.update_traces(line=dict(width=2))

# Add confidence band for the forecast (as filled area)
fig.add_trace(go.Scatter(
    x=list(future_dates) + list(future_dates[::-1]),
    y=future_hi + future_lo[::-1],
    fill='toself',
    fillcolor='rgba(255,127,14,0.15)',
    line=dict(color='rgba(255,255,255,0)'),
    name='95% Confidence Band',
    showlegend=True,
    hoverinfo='skip'
))

# Overlay actual known monthly data points
fig.add_trace(go.Scatter(
    x=df['Dates'], y=df['Prices'],
    mode='markers',
    marker=dict(color='black', size=6, symbol='circle'),
    name='Actual monthly data'
))

# Vertical line marking "today" (last known data point)
fig.add_vline(
    x=model.last_date.timestamp() * 1000,
    line_dash='dot', line_color='gray',
    annotation_text='Last known data', annotation_position='top left'
)

fig.update_layout(
    template='plotly_white',
    xaxis_title='Date',
    yaxis_title='Price ($/MMBtu)',
    legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
    hovermode='x unified',
    width=1000,
    height=550
)

fig.show()

print(f"\nForecast range: {future_dates[0].date()} to {future_dates[-1].date()}")
print(f"Forecast price range: {min(future_prices):.2f} to {max(future_prices):.2f}")
print(f"Widest confidence interval at end of forecast: [{future_lo[-1]:.2f}, {future_hi[-1]:.2f}]")

"""The **interactive chart** shows the historical interpolated line (blue), actual monthly data points (black dots), the 1-year forecast (orange), and a shaded 95% confidence band that widens the further out the forecast goes.

**Forecast summary (Oct 2024 → Sep 2025)**:

Range: $11.83 – $12.95
Confidence widens from tight near the last known point to [$11.54, $12.95] by month 12 — reflecting growing uncertainty the further you extrapolate.
"""

